export default {
  "12ae150c": [() => import(/* webpackChunkName: "12ae150c" */ "@site/docs/workflows/index.md"), "@site/docs/workflows/index.md", require.resolveWeak("@site/docs/workflows/index.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1b377a72": [() => import(/* webpackChunkName: "1b377a72" */ "@site/docs/features/agency-dashboard.md"), "@site/docs/features/agency-dashboard.md", require.resolveWeak("@site/docs/features/agency-dashboard.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "6f1db649": [() => import(/* webpackChunkName: "6f1db649" */ "@site/docs/features/animation-studio.md"), "@site/docs/features/animation-studio.md", require.resolveWeak("@site/docs/features/animation-studio.md")],
  "9bc47580": [() => import(/* webpackChunkName: "9bc47580" */ "@site/docs/features/create-photoshoot.md"), "@site/docs/features/create-photoshoot.md", require.resolveWeak("@site/docs/features/create-photoshoot.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aace3873": [() => import(/* webpackChunkName: "aace3873" */ "@site/docs/features/ai-magic-studio.md"), "@site/docs/features/ai-magic-studio.md", require.resolveWeak("@site/docs/features/ai-magic-studio.md")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "b5f059d7": [() => import(/* webpackChunkName: "b5f059d7" */ "@generated/docusaurus-plugin-content-docs/default/p/creativioai-kb-def.json"), "@generated/docusaurus-plugin-content-docs/default/p/creativioai-kb-def.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/creativioai-kb-def.json")],
  "c0742808": [() => import(/* webpackChunkName: "c0742808" */ "@site/docs/features/index.md"), "@site/docs/features/index.md", require.resolveWeak("@site/docs/features/index.md")],
  "c377a04b": [() => import(/* webpackChunkName: "c377a04b" */ "@site/docs/index.md"), "@site/docs/index.md", require.resolveWeak("@site/docs/index.md")],
  "d589d3a7": [() => import(/* webpackChunkName: "d589d3a7" */ "@site/docs/getting-started.md"), "@site/docs/getting-started.md", require.resolveWeak("@site/docs/getting-started.md")],
  "e8c23b91": [() => import(/* webpackChunkName: "e8c23b91" */ "@site/docs/features/brand-kit.md"), "@site/docs/features/brand-kit.md", require.resolveWeak("@site/docs/features/brand-kit.md")],
  "fa291c72": [() => import(/* webpackChunkName: "fa291c72" */ "@site/docs/features/ai-magic-tools.md"), "@site/docs/features/ai-magic-tools.md", require.resolveWeak("@site/docs/features/ai-magic-tools.md")],};
